concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "FoodDeliveryRunner"
  url = "https://git.fhict.nl/"
  id = 7025
  token = "YtkwA7skjjsDdv5h9V4n"
  token_obtained_at = 2022-09-16T14:47:31Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
